classdef MeasurementRunMetric < double
    enumeration
        ID (1)
        Site (2)
        TxPos (3)
        TxHeight (4)
        Freq (5)
        Polarization (6)
        Obstructed (7)
        Waveguided (8)
        Range_m (9)
        Range_l (10)
        CoordX (11)
        CoordY (12)
        LOS (13)
        RicianK (14)
        RMSDelaySpread (15)
        MeanDelay (16)
        MaxDelay (17)
        PathGain (18)
    end

    methods (Static)
        function names = getNames()
            names = [ ...
                "ID", ...
                "Site", ...
                "TxPos", ...
                "TxHeight", ...
                "Freq", ...
                "Polarization", ...
                "Obstructed", ...
                "Waveguided", ...
                "Range_m", ...
                "Range_l", ...
                "CoordX", ...
                "CoordY", ...
                "LOS", ...
                "RicianK", ...
                "DelaySpread", ...
                "MeanDelay", ...
                "MaxDelay", ...
                "PathGain" ];
        end

        function types = getTypes()
            types = [ ...
                "double", ...
                "string", ...
                "double", ...
                "double", ...
                "double", ...
                "string", ...
                "double", ...
                "double", ...
                "double", ...
                "double", ...
                "double", ...
                "double", ...
                "double", ...
                "double", ...
                "double", ...
                "double", ...
                "double", ...
                "double" ];       
        end
    end

    methods (Static)
        function n = getNumBaseColumns()
            n = 12;
        end
    end

    methods 
        function s = getName(obj)
            s = MeasurementRunMetric.getNames{double(obj)};
        end
        
        function s = getType(obj)             
            s = MeasurementRunMetric.getTypes{double(obj)};            
        end

        % function s_arr = getNamesList(obj)
        %     s_arr = {};
        %     for ii = 1:17
        %         s_arr{ii} = MeasurementRunMetric(ii).getName();
        %     end
        % end
    end
end